# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lotto.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import random as rnd


class Ui_Form(object):

    def estrazioni(self):
        contatore = 1
        while contato <= 5:
            a = rnd.randint(1,90)
            a = str(a)
            self.lineEdit_2.setText(str(contatore))
            self.lineEdit.setText(a)
            contatore = contatore + 1




    
    def setupUi(self, Form):
        Form.setObjectName("Form") 
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        Form.setStyleSheet("background-color: rgb(222, 221, 218);")
        self.lb_intestazione = QtWidgets.QLabel(Form)
        self.lb_intestazione.setGeometry(QtCore.QRect(80, 20, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lb_intestazione.setFont(font)
        self.lb_intestazione.setStyleSheet("background-color: rgb(255, 163, 72);\n"
"color: rgb(255, 255, 255);")
        self.lb_intestazione.setFrameShape(QtWidgets.QFrame.Box)
        self.lb_intestazione.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_intestazione.setObjectName("lb_intestazione")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.clicked.connect(self.estrazioni)
        self.pushButton.setGeometry(QtCore.QRect(100, 210, 201, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(26, 95, 180);\n"
"background-color: rgb(229, 165, 10);")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(310, 90, 71, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 110, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 90, 71, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "LOTTO"))
        self.lb_intestazione.setText(_translate("Form", "IL LOTTO"))
        self.pushButton.setText(_translate("Form", "ESTRATTI"))
        self.label.setText(_translate("Form", "Estratto n°: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
